"use client";

import { ArrowRight, CheckCircle2, ClipboardCheck, Eye } from "lucide-react";
import Link from "next/link";

import { InlineError, SurfaceSkeleton } from "@/components/primitives";
import { ReconciliationRail } from "@/components/metrics";
import { formatDate } from "@/lib/format";
import { useBatches } from "@/lib/hooks";

export default function BatchesPage() {
  const { batches, loading, error, refresh } = useBatches();
  return (
    <div className="page-wrap">
      <header className="page-heading"><div><p className="eyebrow">Reconciliation runs</p><h1>Every run has a scope.</h1><p className="page-intro">Open one batch to inspect only the ledger facts generated by that reconciliation run.</p></div><span className="batch-stamp"><span>History</span><strong>{batches.length} recorded runs</strong></span></header>
      {loading ? <SurfaceSkeleton lines={9} /> : error ? <InlineError error={error} retry={refresh} /> : <section className="surface batch-table-wrap"><table className="batch-table"><thead><tr><th>Batch run</th><th>Recorded activity</th><th>Reconciliation breakdown</th><th>Automated rate</th><th>Controller queue</th><th aria-label="Open" /></tr></thead><tbody>{batches.map((batch) => <tr key={batch.batch_run_id}><td><code className="batch-id">{batch.batch_run_id}</code><small>{batch.total} settlements recorded</small></td><td className="muted">{formatDate(batch.last_activity_at, true)}</td><td><ReconciliationRail summary={batch} /></td><td><strong className="batch-rate">{batch.match_rate}%</strong><small>auto-reconciled</small></td><td>{batch.needs_review ? <Link href={`/review?batch=${encodeURIComponent(batch.batch_run_id)}`} className="needs-link"><ClipboardCheck size={15} />{batch.needs_review} needs review</Link> : <span className="queue-clear"><CheckCircle2 size={15} />Clear</span>}</td><td><Link href={`/?batch=${encodeURIComponent(batch.batch_run_id)}`} className="row-action" aria-label={`Open batch ${batch.batch_run_id}`}><Eye size={17} /><ArrowRight size={14} /></Link></td></tr>)}</tbody></table></section>}
    </div>
  );
}
