"""
Versioned SQL migration runner for Razorpay Vulcan Ledger.

Replaces "someone hand-applies ddl.sql" -- which is not reproducible and gives
no way to evolve the schema -- with an ordered, checksummed, idempotent set of
migrations recorded in the database itself.

Deliberately not Alembic: this project's schema is three tables of hand-written
DDL with data-repair steps (deduplicating existing bank credits, pre-flight
RAISE EXCEPTION guards) that read far more clearly as SQL than as autogenerated
Python operations. Adding Alembic would mean a new dependency, an env.py, and a
second source of truth for a schema this size. Plain numbered .sql files plus
this runner keep the schema auditable in one place.

Usage (from backend/, venv active):
    python -m scripts.migrate            # apply everything pending
    python -m scripts.migrate --status   # show applied/pending, apply nothing

Exception vectors handled:
    - A migration file edited after it was applied -> checksum mismatch, hard
      abort. Silently re-running an edited migration is how two environments
      end up with different schemas that both claim to be at the same version.
    - A migration failing halfway -> each file runs in its own transaction, so
      it either fully applies and is recorded, or fully rolls back and is not.
    - Database unreachable -> psycopg.OperationalError propagates with a clear
      message; the runner does not retry, because a human needs to start
      Postgres.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import time
from pathlib import Path

import psycopg

from config.settings import get_settings

MIGRATIONS_DIR = Path(__file__).resolve().parent.parent / "database" / "migrations"

_BOOTSTRAP_SQL = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version       VARCHAR(100) PRIMARY KEY,
    checksum      VARCHAR(64)  NOT NULL,
    applied_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    execution_ms  INTEGER      NOT NULL
);
"""

def _checksum(sql: str) -> str:
    """SHA-256 of a migration's text, used to detect post-application edits."""
    return hashlib.sha256(sql.encode("utf-8")).hexdigest()


def discover_migrations() -> list[tuple[str, str, str]]:
    """
    Read every migration file in lexicographic (= version) order.

    Returns:
        A list of (version, sql, checksum). Version is the filename stem, e.g.
        "001_baseline", so zero-padded prefixes keep ordering correct past 9.

    Raises:
        FileNotFoundError: if the migrations directory is missing entirely,
            which means the checkout is incomplete -- not something to paper
            over with an empty list.
    """
    if not MIGRATIONS_DIR.is_dir():
        raise FileNotFoundError(f"migrations directory not found: {MIGRATIONS_DIR}")

    migrations: list[tuple[str, str, str]] = []
    for path in sorted(MIGRATIONS_DIR.glob("*.sql")):
        sql = path.read_text(encoding="utf-8")
        migrations.append((path.stem, sql, _checksum(sql)))
    return migrations


def _applied(conn: psycopg.Connection) -> dict[str, str]:
    """Return {version: checksum} for every migration already recorded."""
    with conn.cursor() as cur:
        cur.execute("SELECT version, checksum FROM schema_migrations")
        return dict(cur.fetchall())


def _verify_no_drift(migrations: list[tuple[str, str, str]], applied: dict[str, str]) -> None:
    """
    Abort if an already-applied migration's text has changed on disk.

    Raises:
        RuntimeError: listing every drifted version. The correct fix is a new
            migration file, never an edit to an applied one.
    """
    drifted = [
        version
        for version, _sql, checksum in migrations
        if version in applied and applied[version] != checksum
    ]
    if drifted:
        raise RuntimeError(
            "Migration files changed after being applied: "
            + ", ".join(drifted)
            + ". Never edit an applied migration -- add a new one instead."
        )


def run_migrations(dsn: str, *, dry_run: bool = False) -> list[str]:
    """
    Apply every pending migration, in order, each in its own transaction.

    Args:
        dsn: synchronous postgresql:// DSN (settings.sync_database_url).
        dry_run: report what would run and change nothing.

    Returns:
        The versions applied (empty if already up to date, or if dry_run).

    Exception vectors handled:
        A failing migration rolls back its own transaction and is NOT recorded,
        so re-running after the fix retries exactly that file. Earlier
        migrations that already succeeded stay applied and are not repeated.
    """
    migrations = discover_migrations()
    newly_applied: list[str] = []

    with psycopg.connect(dsn) as conn:
        with conn.cursor() as cur:
            cur.execute(_BOOTSTRAP_SQL)
        conn.commit()

        applied = _applied(conn)
        _verify_no_drift(migrations, applied)

        pending = [(v, sql, cs) for v, sql, cs in migrations if v not in applied]

        if not pending:
            print(f"[migrate] up to date -- {len(applied)} migration(s) applied")
            return []

        for version, sql, checksum in pending:
            if dry_run:
                print(f"[migrate] PENDING {version}")
                continue

            print(f"[migrate] applying {version} ...")
            started = time.perf_counter()
            try:
                with conn.cursor() as cur:
                    cur.execute(sql)
                    cur.execute(
                        "INSERT INTO schema_migrations (version, checksum, execution_ms) "
                        "VALUES (%s, %s, %s)",
                        (version, checksum, int((time.perf_counter() - started) * 1000)),
                    )
                conn.commit()
            except Exception:
                conn.rollback()
                print(f"[migrate] FAILED {version} -- rolled back, nothing recorded", file=sys.stderr)
                raise
            newly_applied.append(version)
            print(f"[migrate] applied  {version} ({int((time.perf_counter() - started) * 1000)} ms)")

    return newly_applied


def print_status(dsn: str) -> None:
    """Print each migration as APPLIED (with timestamp) or PENDING."""
    migrations = discover_migrations()
    with psycopg.connect(dsn) as conn:
        with conn.cursor() as cur:
            cur.execute(_BOOTSTRAP_SQL)
        conn.commit()
        with conn.cursor() as cur:
            cur.execute("SELECT version, checksum, applied_at FROM schema_migrations")
            rows = {v: (cs, at) for v, cs, at in cur.fetchall()}

    for version, _sql, checksum in migrations:
        if version not in rows:
            print(f"  PENDING  {version}")
            continue
        recorded_checksum, applied_at = rows[version]
        drift = "" if recorded_checksum == checksum else "  [!! FILE CHANGED SINCE APPLIED]"
        print(f"  APPLIED  {version}  {applied_at:%Y-%m-%d %H:%M:%S}{drift}")


def main() -> int:
    """CLI entry point. Returns a process exit code."""
    parser = argparse.ArgumentParser(description="Apply Vulcan Ledger schema migrations.")
    parser.add_argument("--status", action="store_true", help="show applied/pending, change nothing")
    parser.add_argument("--dry-run", action="store_true", help="list pending migrations without applying")
    args = parser.parse_args()

    dsn = get_settings().sync_database_url

    if args.status:
        print_status(dsn)
        return 0

    run_migrations(dsn, dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
